window.DB_DATA = {
  games: [
    {id:'jade-jungle',name:'Jade Jungle',studio:'Northstar Studio',category:'Adventure',art:6,rating:4.8,reviews:128,tag:'EDITOR’S PICK',theme:'Emerald ruins & wild discoveries',pace:'Measured',volatility:'High',rtp:'96.2%',mechanic:'Cluster pays',release:'2026-08-12',platforms:['orbit','vault','flux'],description:'Step into a forgotten jungle where luminous jade guardians keep watch over ancient ruins. Cascading symbols and expanding wilds give this atmospheric adventure a rhythm of its own.',likes:['Beautifully layered jungle soundscape','Cascades that are easy to follow','A distinctive guardian transformation'],tradeoff:'Long animation sequences can feel slow if you prefer a quicker pace.'},
    {id:'neon-nights',name:'Neon Nights',studio:'Electric House',category:'Arcade',art:0,rating:4.7,reviews:96,tag:'COMMUNITY FAVORITE',theme:'Fast lanes. Late nights.',pace:'Fast',volatility:'High',rtp:'96.0%',mechanic:'Expanding reels',release:'2026-08-28',platforms:['orbit','flux','nova'],description:'A neon-soaked ride through a rain-slick city. Expanding reels, a synthwave soundtrack, and punchy transitions make this a favorite for players who care about presentation.',likes:['Excellent synthwave soundtrack','Crisp, readable symbols on mobile','A strong sense of momentum'],tradeoff:'The flashes and fast transitions may be too intense for some players.'},
    {id:'temple-tides',name:'Temple of Tides',studio:'Northstar Studio',category:'Adventure',art:1,rating:4.6,reviews:74,tag:'',theme:'A world below the surface',pace:'Relaxed',volatility:'Medium',rtp:'96.1%',mechanic:'Cascading reels',release:'2026-07-19',platforms:['vault','nova','arc'],description:'Explore an underwater sanctuary filled with turquoise light and forgotten treasures. Gentle transitions and an understated soundtrack create a calmer way to experience cascading reels.',likes:['Rich underwater art direction','A clear and welcoming rules screen','Unhurried animations'],tradeoff:'The base-game presentation can become repetitive over longer sessions.'},
    {id:'wild-frontier',name:'Wild Frontier',studio:'Dust & Gold',category:'Classic',art:2,rating:4.5,reviews:83,tag:'',theme:'A little dust. A lot of character.',pace:'Measured',volatility:'Medium',rtp:'96.3%',mechanic:'Paylines',release:'2026-06-21',platforms:['orbit','vault','arc'],description:'Warm sunset colors, hand-painted symbols, and a guitar-led score bring a western town to life. Familiar paylines make it especially easy to understand what is happening on the reels.',likes:['Clear, traditional payline structure','A warm and cohesive visual style','Useful animation speed controls'],tradeoff:'Players looking for unusual mechanics may find it familiar.'},
    {id:'moonlight-heist',name:'Moonlight Heist',studio:'Velvet Labs',category:'Adventure',art:3,rating:4.7,reviews:61,tag:'NEW RELEASE',theme:'The city sleeps. You don’t.',pace:'Measured',volatility:'High',rtp:'96.0%',mechanic:'Collection feature',release:'2026-09-08',platforms:['flux','nova','playroom'],description:'Follow a rooftop thief through a violet cityscape. A collection mechanic unfolds in chapters, with small visual details that reward paying attention to the story.',likes:['A playful story told through animation','Distinctive character design','Satisfying chapter transitions'],tradeoff:'The collection rules take a little more time to learn.'},
    {id:'candy-circuit',name:'Candy Circuit',studio:'Electric House',category:'Arcade',art:4,rating:4.4,reviews:105,tag:'',theme:'A sugar-coated arcade daydream',pace:'Fast',volatility:'Medium',rtp:'96.2%',mechanic:'Cluster pays',release:'2026-07-04',platforms:['orbit','flux','playroom'],description:'Candy-colored tracks wind through a miniature amusement park. Chunky symbols and lively cluster animations keep everything readable, even on a smaller screen.',likes:['Excellent small-screen readability','Cheerful visual personality','Simple cluster mechanics'],tradeoff:'The bright colors and repeated audio cues will not suit every taste.'},
    {id:'cosmic-drift',name:'Cosmic Drift',studio:'Velvet Labs',category:'Sci-fi',art:5,rating:4.8,reviews:89,tag:'',theme:'Get a little lost in space',pace:'Relaxed',volatility:'Medium',rtp:'96.4%',mechanic:'Cascading reels',release:'2026-08-02',platforms:['vault','nova','playroom'],description:'Float through a deep-space dreamscape of orbiting planets and slow-moving stars. An ambient soundtrack and restrained effects give this sci-fi title an unusually thoughtful atmosphere.',likes:['Immersive ambient sound design','Comfortable contrast and readable symbols','A cohesive science-fiction world'],tradeoff:'Its deliberately quiet presentation can feel understated.'},
    {id:'koi-garden',name:'Koi Garden',studio:'Northstar Studio',category:'Classic',art:7,rating:4.6,reviews:57,tag:'',theme:'Find your flow',pace:'Relaxed',volatility:'Low',rtp:'96.1%',mechanic:'Paylines',release:'2026-08-16',platforms:['orbit','arc','playroom'],description:'Glowing koi glide across an ink-dark pond in this beautifully restrained game. Familiar reels, soft water sounds, and deliberate animation make the experience easy to settle into.',likes:['Exceptional water and lighting effects','Simple, clearly explained mechanics','A gentle soundscape'],tradeoff:'There are fewer mechanical surprises than in more elaborate titles.'},
    {id:'afterburn',name:'Afterburn',studio:'Electric House',category:'Arcade',art:0,rating:4.3,reviews:42,tag:'NEW RELEASE',theme:'One more lap around the city',pace:'Fast',volatility:'High',rtp:'96.0%',mechanic:'Collection feature',release:'2026-09-11',platforms:['flux','nova'],description:'A racing-inspired arcade experience built around collectible car upgrades and night-city scenery. Short transitions and a compact interface keep the presentation moving.',likes:['A compact and intuitive interface','Distinctive racing-inspired symbols','Good control over animation speed'],tradeoff:'The visual effects can get busy when several features overlap.'},
    {id:'deep-blue',name:'Deep Blue',studio:'Velvet Labs',category:'Adventure',art:1,rating:4.4,reviews:38,tag:'',theme:'Beyond the last ray of light',pace:'Relaxed',volatility:'Medium',rtp:'96.2%',mechanic:'Expanding reels',release:'2026-05-26',platforms:['vault','arc'],description:'An atmospheric expedition beneath the ocean surface, with expanding reels framed by bioluminescent coral and a subtle cinematic score.',likes:['A considered color palette','Smooth reel transitions','An uncluttered mobile layout'],tradeoff:'The feature explanations could be easier to find.'},
    {id:'stardust-station',name:'Stardust Station',studio:'Northstar Studio',category:'Sci-fi',art:5,rating:4.5,reviews:46,tag:'',theme:'Your next stop is somewhere else',pace:'Measured',volatility:'Medium',rtp:'96.3%',mechanic:'Cluster pays',release:'2026-06-11',platforms:['orbit','nova','playroom'],description:'A small station at the edge of a colorful galaxy becomes the stage for clean cluster mechanics and playful astronaut animations.',likes:['Friendly character animations','A readable cluster layout','A memorable ambient soundtrack'],tradeoff:'The visual variety is limited outside the main feature.'},
    {id:'sundown-saloon',name:'Sundown Saloon',studio:'Dust & Gold',category:'Classic',art:2,rating:4.2,reviews:34,tag:'',theme:'Pull up a chair',pace:'Measured',volatility:'Low',rtp:'96.1%',mechanic:'Paylines',release:'2026-04-18',platforms:['orbit','arc'],description:'An old-school reel layout set inside a warmly lit frontier saloon. A small set of well-explained features keeps the experience approachable.',likes:['Easy-to-read rules','A classic, minimal reel layout','Comfortable animation timing'],tradeoff:'The soundtrack loops noticeably and the feature set is small.'}
  ],
  platforms:[
    {id:'orbit',name:'Orbit',symbol:'O',color:'#c6ff62',tag:'Best all-round experience',rating:4.7,reviews:246,games:2400,studios:42,kyc:'Required',support:'24/7 live chat',response:'Under 5 min',withdrawal:'15–60 min',minimum:'$10',fee:'Network fee',mobile:4.8,service:4.6,variety:4.8,clarity:4.5,region:'Selected markets',description:'A spacious, easy-to-navigate catalog with a particularly strong mobile experience. Useful search tools and clear game categories make it easy to find something that fits your taste.',strengths:['Excellent mobile navigation','Clear account and payment settings','Broad range of game studios'],consideration:'Identity verification is required before withdrawals.',updated:'Sep 12, 2026'},
    {id:'vault',name:'Vault',symbol:'V',color:'#b3a2fa',tag:'For the detail-oriented player',rating:4.6,reviews:184,games:1800,studios:34,kyc:'Required',support:'24/7 live chat',response:'5–10 min',withdrawal:'30–120 min',minimum:'$15',fee:'Network fee',mobile:4.5,service:4.7,variety:4.5,clarity:4.8,region:'Selected markets',description:'A considered platform that puts game information and account controls within easy reach. Especially appealing to players who like to understand the details before choosing.',strengths:['Well-organized game information','Detailed help center','Readable account policies'],consideration:'Some less common game studios are not available.',updated:'Sep 10, 2026'},
    {id:'flux',name:'Flux',symbol:'F',color:'#ff9a72',tag:'Fresh releases, front and center',rating:4.5,reviews:162,games:2100,studios:38,kyc:'Required',support:'Live chat · 08:00–24:00 UTC',response:'5–15 min',withdrawal:'1–4 hours',minimum:'$10',fee:'Network fee',mobile:4.7,service:4.3,variety:4.7,clarity:4.4,region:'Selected markets',description:'A visually energetic catalog focused on new releases and arcade-inspired games. Studio pages and recently added filters make discovery especially enjoyable.',strengths:['Frequent catalog updates','Strong studio discovery pages','Responsive mobile interface'],consideration:'Live support is not available around the clock.',updated:'Sep 11, 2026'},
    {id:'nova',name:'Nova',symbol:'N',color:'#8cb9ff',tag:'A home for adventurous tastes',rating:4.4,reviews:137,games:1600,studios:29,kyc:'Required',support:'24/7 live chat',response:'10–20 min',withdrawal:'1–6 hours',minimum:'$20',fee:'Network fee',mobile:4.5,service:4.2,variety:4.4,clarity:4.5,region:'Selected markets',description:'A focused game library with strong sci-fi and adventure categories. Clean layouts and concise explanations help new visitors find their way around.',strengths:['Focused thematic collections','Clean game detail screens','Easy-to-find support'],consideration:'The minimum withdrawal is higher than some alternatives.',updated:'Sep 9, 2026'},
    {id:'arc',name:'Arc',symbol:'A',color:'#edcf87',tag:'The classics, thoughtfully curated',rating:4.3,reviews:98,games:1200,studios:24,kyc:'Required',support:'Email & daytime live chat',response:'15–30 min',withdrawal:'2–12 hours',minimum:'$10',fee:'Network fee',mobile:4.3,service:4.2,variety:4.1,clarity:4.6,region:'Selected markets',description:'A smaller, carefully organized catalog with a particular emphasis on familiar mechanics and quieter visual experiences.',strengths:['Clear classic-game categories','Straightforward navigation','Readable terms and help pages'],consideration:'The catalog is smaller and support hours are limited.',updated:'Sep 8, 2026'},
    {id:'playroom',name:'Playroom',symbol:'P',color:'#f7a9d2',tag:'Made for curious explorers',rating:4.4,reviews:116,games:1500,studios:31,kyc:'Required',support:'24/7 live chat',response:'5–15 min',withdrawal:'1–8 hours',minimum:'$15',fee:'Network fee',mobile:4.6,service:4.3,variety:4.4,clarity:4.3,region:'Selected markets',description:'A colorful discovery-focused experience with friendly studio introductions and thematic collections for different tastes.',strengths:['Helpful introductory game guides','Easy to browse on mobile','Good thematic variety'],consideration:'Withdrawal reviews can take longer during busy periods.',updated:'Sep 12, 2026'}
  ],
  creators:[
    {id:'maya',name:'Maya Chen',handle:'@mayaplays',initials:'MC',color:'#dac5ff',role:'The art-direction enthusiast',bio:'Here for beautiful worlds, thoughtful sound design, and games with a point of view.',followers:1240,reviews:38,focus:'Art & atmosphere'},
    {id:'leo',name:'Leo Park',handle:'@leospins',initials:'LP',color:'#ffbe97',role:'Your mechanics translator',bio:'I read the rules so you can understand the experience. Clear explanations, honest tradeoffs.',followers:986,reviews:52,focus:'Game mechanics'},
    {id:'nina',name:'Nina Rivers',handle:'@ninar',initials:'NR',color:'#a9d4fa',role:'Small screen, big opinions',bio:'Every game on a phone. Every tiny button noticed. Mobile experience matters.',followers:842,reviews:29,focus:'Mobile experience'}
  ],
  collections:[
    {id:'after-dark',name:'After dark, on another planet',subtitle:'Neon cities, distant galaxies, and a little escapism.',author:'maya',games:['neon-nights','cosmic-drift','moonlight-heist','stardust-station'],art:0,saves:328,tag:'THE NIGHT SHIFT'},
    {id:'slow-lane',name:'Take the scenic route',subtitle:'Beautiful worlds that let the atmosphere breathe.',author:'maya',games:['koi-garden','temple-tides','cosmic-drift','deep-blue'],art:7,saves:246,tag:'LESS RUSH. MORE ATMOSPHERE.'},
    {id:'first-impressions',name:'Easy to get. Hard to forget.',subtitle:'Clear mechanics and a whole lot of personality.',author:'leo',games:['wild-frontier','candy-circuit','koi-garden','sundown-saloon'],art:4,saves:192,tag:'THE APPROACHABLE EDIT'}
  ],
  reviews:[
    {id:'r1',type:'game',target:'jade-jungle',author:'maya',rating:5,title:'The sound design deserves headphones.',body:'The little details make this one. Water in the distance, the movement of the leaves, the guardian animation. The pacing is deliberate, which I like — but turn down the effects if you prefer a quieter screen.',date:'Sep 12, 2026',helpful:24},
    {id:'r2',type:'game',target:'neon-nights',author:'nina',rating:4,title:'A neon city that actually fits on your phone.',body:'Everything is readable on a smaller screen and the controls stay out of the way. I would love a reduced-flash option. The soundtrack is an easy highlight.',date:'Sep 11, 2026',helpful:18},
    {id:'r3',type:'platform',target:'orbit',author:'leo',rating:5,title:'Finding a game takes seconds.',body:'The filters are useful, account settings are clear, and the mobile catalog never feels cramped. I appreciated that the identity-check steps were explained before reaching the withdrawal screen.',date:'Sep 10, 2026',helpful:31},
    {id:'r4',type:'game',target:'cosmic-drift',author:'maya',rating:5,title:'An unusually good place to slow down.',body:'The ambient score and soft lighting are a lovely combination. The rules are straightforward, but the presentation has enough character to make it memorable.',date:'Sep 9, 2026',helpful:16},
    {id:'r5',type:'platform',target:'vault',author:'nina',rating:4,title:'The details are easy to find.',body:'Good help pages and clear game information. A couple of settings take one tap too many on mobile, but the overall layout is thoughtful.',date:'Sep 8, 2026',helpful:12}
  ]
};
